name: Build GKI

on:
  workflow_dispatch:
   inputs:
    KSU:
     description: 'Do you want to use KSU?'
     required: true
     default: 'No'
     type: choice
     options:
     - 'Yes'
     - 'No'
     
jobs:
  build:
    name: Build GKI Kernel 
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Free up storage
      uses: rokibhasansagar/slimhub_actions@main

    - name: Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10

    - name: Build
      run: |
       [ -x "build.sh" ] || chmod a+x build.sh
       [ "${{ inputs.KSU }}" = "Yes" ] && export USE_KSU=1
       export chat_id="${{ secrets.CHAT_ID }}"
       export token="${{ secrets.TOKEN }}"
       ./build.sh
